/// error : false
/// message : "get banks Successfully."
/// data : [{"BANK":"ABHYUDAYA COOPERATIVE BANK LIMITED"},{"BANK":"ABU DHABI COMMERCIAL BANK"},{"BANK":"ADITYA BIRLA IDEA PAYMENTS BANK"},{"BANK":"AHMEDABAD MERCANTILE COOPERATIVE BANK"},{"BANK":"AIRTEL PAYMENTS BANK LIMITED"},{"BANK":"AKOLA JANATA COMMERCIAL COOPERATIVE BANK"},{"BANK":"ALLAHABAD BANK"},{"BANK":"ALMORA URBAN COOPERATIVE BANK LIMITED"},{"BANK":"ANDHRA BANK"},{"BANK":"ANDHRA PRAGATHI GRAMEENA BANK"},{"BANK":"APNA SAHAKARI BANK LIMITED"},{"BANK":"AU SMALL FINANCE BANK LIMITED"},{"BANK":"AUSTRALIA AND NEW ZEALAND BANKING GROUP LIMITED"},{"BANK":"AXIS BANK"},{"BANK":"B N P PARIBAS"},{"BANK":"BANDHAN BANK LIMITED"},{"BANK":"BANK INTERNASIONAL INDONESIA"},{"BANK":"BANK OF AMERICA"},{"BANK":"BANK OF BAHARAIN AND KUWAIT BSC"},{"BANK":"BANK OF BARODA"},{"BANK":"BANK OF CEYLON"},{"BANK":"BANK OF INDIA"},{"BANK":"BANK OF MAHARASHTRA"},{"BANK":"BANK OF TOKYO MITSUBISHI LIMITED"},{"BANK":"BARCLAYS BANK"},{"BANK":"BASSEIN CATHOLIC COOPERATIVE BANK LIMITED"},{"BANK":"BHARAT COOPERATIVE BANK MUMBAI LIMITED"},{"BANK":"CANARA BANK"},{"BANK":"CAPITAL SMALL FINANCE BANK LIMITED"},{"BANK":"CATHOLIC SYRIAN BANK LIMITED"},{"BANK":"CENTRAL BANK OF INDIA"},{"BANK":"CHINATRUST COMMERCIAL BANK LIMITED"},{"BANK":"CITI BANK"},{"BANK":"CITIZEN CREDIT COOPERATIVE BANK LIMITED"},{"BANK":"CITY UNION BANK LIMITED"},{"BANK":"COMMONWEALTH BANK OF AUSTRALIA"},{"BANK":"CORPORATION BANK"},{"BANK":"CREDIT AGRICOLE CORPORATE AND INVESTMENT BANK CALYON BANK"},{"BANK":"CREDIT SUISEE AG"},{"BANK":"DCB BANK LIMITED"},{"BANK":"DENA BANK"},{"BANK":"DEOGIRI NAGARI SAHAKARI BANK LTD. AURANGABAD"},{"BANK":"DEPOSIT INSURANCE AND CREDIT GUARANTEE CORPORATION"},{"BANK":"DEUSTCHE BANK"},{"BANK":"DEVELOPMENT BANK OF SINGAPORE"},{"BANK":"DHANALAKSHMI BANK"},{"BANK":"DMK JAOLI BANK"},{"BANK":"DOHA BANK"},{"BANK":"DOHA BANK QSC"},{"BANK":"DOMBIVLI NAGARI SAHAKARI BANK LIMITED"},{"BANK":"DURGAPUR STEEL PEOPLES CO-OPERATIVE BANK LTD"},{"BANK":"EMIRATES NBD BANK P J S C"},{"BANK":"EQUITAS SMALL FINANCE BANK LIMITED"},{"BANK":"ESAF SMALL FINANCE BANK LIMITED"},{"BANK":"EXPORT IMPORT BANK OF INDIA"},{"BANK":"FEDERAL BANK"},{"BANK":"FINCARE SMALL FINANCE BANK LTD"},{"BANK":"FINO PAYMENTS BANK"},{"BANK":"FIRST ABU DHABI BANK PJSC"},{"BANK":"FIRSTRAND BANK LIMITED"},{"BANK":"G P PARSIK BANK"},{"BANK":"GURGAON GRAMIN BANK"},{"BANK":"HDFC BANK"},{"BANK":"HIMACHAL PRADESH STATE COOPERATIVE BANK LTD"},{"BANK":"HSBC BANK"},{"BANK":"HSBC BANK OMAN SAOG"},{"BANK":"ICICI BANK LIMITED"},{"BANK":"IDBI BANK"},{"BANK":"IDFC BANK LIMITED"},{"BANK":"IDUKKI DISTRICT CO OPERATIVE BANK LTD"},{"BANK":"INDIA POST PAYMENT BANK"},{"BANK":"INDIAN BANK"},{"BANK":"INDIAN OVERSEAS BANK"},{"BANK":"INDUSIND BANK"},{"BANK":"INDUSTRIAL AND COMMERCIAL BANK OF CHINA LIMITED"},{"BANK":"INDUSTRIAL BANK OF KOREA"},{"BANK":"JALGAON JANATA SAHAKARI BANK LIMITED"},{"BANK":"JAMMU AND KASHMIR BANK LIMITED"},{"BANK":"JANA SMALL FINANCE BANK LTD"},{"BANK":"JANAKALYAN SAHAKARI BANK LIMITED"},{"BANK":"JANASEVA SAHAKARI BANK BORIVLI LIMITED"},{"BANK":"JANASEVA SAHAKARI BANK LIMITED"},{"BANK":"JANATA SAHAKARI BANK LIMITED"},{"BANK":"JIO PAYMENTS BANK LIMITED"},{"BANK":"JP MORGAN BANK"},{"BANK":"KALLAPPANNA AWADE ICHALKARANJI JANATA SAHAKARI BANK LIMITED"},{"BANK":"KALUPUR COMMERCIAL COOPERATIVE BANK"},{"BANK":"KALYAN JANATA SAHAKARI BANK"},{"BANK":"KAPOL COOPERATIVE BANK LIMITED"},{"BANK":"KARNATAKA BANK LIMITED"},{"BANK":"KARNATAKA VIKAS GRAMEENA BANK"},{"BANK":"KARUR VYSYA BANK"},{"BANK":"KEB Hana Bank"},{"BANK":"KERALA GRAMIN BANK"},{"BANK":"KOTAK MAHINDRA BANK LIMITED"},{"BANK":"KOZHIKODE DISTRICT COOPERATIAVE BANK LTD"},{"BANK":"KRUNG THAI BANK PCL"},{"BANK":"LAXMI VILAS BANK"},{"BANK":"MAHANAGAR COOPERATIVE BANK"},{"BANK":"Maharashtra Gramin Bank"},{"BANK":"MAHARASHTRA STATE COOPERATIVE BANK"},{"BANK":"MASHREQBANK PSC"},{"BANK":"MIZUHO BANK LTD"},{"BANK":"MUFG BANK, LTD"},{"BANK":"NAGAR URBAN CO OPERATIVE BANK"},{"BANK":"NAGPUR NAGARIK SAHAKARI BANK LIMITED"},{"BANK":"NATIONAL AUSTRALIA BANK LIMITED"},{"BANK":"NATIONAL BANK FOR AGRICULTURE AND RURAL DEVELOPMENT"},{"BANK":"NATIONAL BANK OF ABU DHABI PJSC"},{"BANK":"NEW INDIA COOPERATIVE BANK LIMITED"},{"BANK":"NKGSB COOPERATIVE BANK LIMITED"},{"BANK":"NORTH EAST SMALL FINANCE BANK LIMITED"},{"BANK":"NORTH MALABAR GRAMIN BANK"},{"BANK":"NUTAN NAGARIK SAHAKARI BANK LIMITED"},{"BANK":"OMAN INTERNATIONAL BANK SAOG"},{"BANK":"ORIENTAL BANK OF COMMERCE"},{"BANK":"PAYTM PAYMENTS BANK LTD"},{"BANK":"PRAGATHI KRISHNA GRAMIN BANK"},{"BANK":"PRATHAMA BANK"},{"BANK":"PRIME COOPERATIVE BANK LIMITED"},{"BANK":"PT BANK MAYBANK INDONESIA TBK"},{"BANK":"PUNJAB AND MAHARSHTRA COOPERATIVE BANK"},{"BANK":"PUNJAB AND SIND BANK"},{"BANK":"PUNJAB NATIONAL BANK"},{"BANK":"QATAR NATIONAL BANK SAQ"},{"BANK":"RABOBANK INTERNATIONAL"},{"BANK":"RAJARAMBAPU SAHAKARI BANK LIMITED"},{"BANK":"RAJGURUNAGAR SAHAKARI BANK LIMITED"},{"BANK":"RAJKOT NAGRIK SAHAKARI BANK LIMITED"},{"BANK":"RBI PAD, AHMEDABAD"},{"BANK":"RBL Bank Limited"},{"BANK":"RESERVE BANK OF INDIA , PAD"},{"BANK":"RESERVE BANK OF INDIA, PAD"},{"BANK":"SAHEBRAO DESHMUKH COOPERATIVE BANK LIMITED"},{"BANK":"SAMARTH SAHAKARI BANK LTD"},{"BANK":"SARASWAT COOPERATIVE BANK LIMITED"},{"BANK":"SBER BANK"},{"BANK":"SBM BANK MAURITIUS LIMITED"},{"BANK":"SHIKSHAK SAHAKARI BANK LIMITED"},{"BANK":"SHINHAN BANK"},{"BANK":"SHIVALIK MERCANTILE CO OPERATIVE BANK LTD"},{"BANK":"SHRI CHHATRAPATI RAJASHRI SHAHU URBAN COOPERATIVE BANK LIMITED"},{"BANK":"SMALL INDUSTRIES DEVELOPMENT BANK OF INDIA"},{"BANK":"SOCIETE GENERALE"},{"BANK":"SOLAPUR JANATA SAHAKARI BANK LIMITED"},{"BANK":"SOUTH INDIAN BANK"},{"BANK":"STANDARD CHARTERED BANK"},{"BANK":"STATE BANK OF INDIA"},{"BANK":"STATE BANK OF MAURITIUS LIMITED"},{"BANK":"SUMITOMO MITSUI BANKING CORPORATION"},{"BANK":"SURAT NATIONAL COOPERATIVE BANK LIMITED"},{"BANK":"SURYODAY SMALL FINANCE BANK LIMITED"},{"BANK":"SUTEX COOPERATIVE BANK LIMITED"},{"BANK":"SYNDICATE BANK"},{"BANK":"TAMILNAD MERCANTILE BANK LIMITED"},{"BANK":"TELANGANA STATE COOP APEX BANK"},{"BANK":"TEXTILE TRADERS CO OPERATIVE BANK LTD"},{"BANK":"THE A.P. MAHESH COOPERATIVE URBAN BANK LIMITED"},{"BANK":"THE AKOLA DISTRICT CENTRAL COOPERATIVE BANK"},{"BANK":"THE ANDHRA PRADESH STATE COOPERATIVE BANK LIMITED"},{"BANK":"THE BANK OF NOVA SCOTIA"},{"BANK":"THE BARAMATI SAHAKARI BANK LTD"},{"BANK":"THE COSMOS CO OPERATIVE BANK LIMITED"},{"BANK":"THE DELHI STATE COOPERATIVE BANK LIMITED"},{"BANK":"THE GADCHIROLI DISTRICT CENTRAL COOPERATIVE BANK LIMITED"},{"BANK":"THE GREATER BOMBAY COOPERATIVE BANK LIMITED"},{"BANK":"THE GUJARAT STATE COOPERATIVE BANK LIMITED"},{"BANK":"THE HASTI COOP BANK LTD"},{"BANK":"THE JALGAON PEOPELS COOPERATIVE BANK LIMITED"},{"BANK":"THE KANGRA CENTRAL COOPERATIVE BANK LIMITED"},{"BANK":"THE KANGRA COOPERATIVE BANK LIMITED"},{"BANK":"THE KARAD URBAN COOPERATIVE BANK LIMITED"},{"BANK":"THE KARANATAKA STATE COOPERATIVE APEX BANK LIMITED"},{"BANK":"THE KURMANCHAL NAGAR SAHAKARI BANK LIMITED"},{"BANK":"THE MEHSANA URBAN COOPERATIVE BANK"},{"BANK":"THE MUMBAI DISTRICT CENTRAL COOPERATIVE BANK LIMITED"},{"BANK":"THE MUNICIPAL COOPERATIVE BANK LIMITED"},{"BANK":"THE NAINITAL BANK LIMITED"},{"BANK":"THE NASIK MERCHANTS COOPERATIVE BANK LIMITED"},{"BANK":"THE NAVNIRMAN CO-OPERATIVE BANK LIMITED"},{"BANK":"THE PANDHARPUR URBAN CO OP. BANK LTD. PANDHARPUR"},{"BANK":"THE RAJASTHAN STATE COOPERATIVE BANK LIMITED"},{"BANK":"THE ROYAL BANK OF SCOTLAND N V"},{"BANK":"THE SEVA VIKAS COOPERATIVE BANK LIMITED"},{"BANK":"THE SHAMRAO VITHAL COOPERATIVE BANK"},{"BANK":"THE SINDHUDURG DISTRICT CENTRAL COOP BANK LTD"},{"BANK":"THE SURAT DISTRICT COOPERATIVE BANK LIMITED"},{"BANK":"THE SURATH PEOPLES COOPERATIVE BANK LIMITED"},{"BANK":"THE TAMIL NADU STATE APEX COOPERATIVE BANK"},{"BANK":"THE THANE BHARAT SAHAKARI BANK LIMITED"},{"BANK":"THE THANE DISTRICT CENTRAL COOPERATIVE BANK LIMITED"},{"BANK":"THE VARACHHA COOPERATIVE BANK LIMITED"},{"BANK":"THE VISHWESHWAR SAHAKARI BANK LIMITED"},{"BANK":"THE WEST BENGAL STATE COOPERATIVE BANK"},{"BANK":"THE ZOROASTRIAN COOPERATIVE BANK LIMITED"},{"BANK":"THRISSUR DISTRICT CO-OPERATIVE BANK LTD"},{"BANK":"TJSB SAHAKARI BANK LIMITED"},{"BANK":"TJSB SAHAKARI BANK LTD"},{"BANK":"TUMKUR GRAIN MERCHANTS COOPERATIVE BANK LIMITED"},{"BANK":"UCO BANK"},{"BANK":"Ujjivan Small Finance Bank Limited"},{"BANK":"UNION BANK OF INDIA"},{"BANK":"UNITED BANK OF INDIA"},{"BANK":"UNITED OVERSEAS BANK LIMITED"},{"BANK":"UTKARSH SMALL FINANCE BANK"},{"BANK":"VASAI VIKAS SAHAKARI BANK LIMITED"},{"BANK":"VASAI VIKAS SAHAKARI BANK LTD"},{"BANK":"VIJAYA BANK"},{"BANK":"WESTPAC BANKING CORPORATION"},{"BANK":"WOORI BANK"},{"BANK":"YES BANK"},{"BANK":"ZILA SAHAKRI BANK LIMITED GHAZIABAD"}]

class BankNameM {
  BankNameM({
      bool? error, 
      String? message, 
      List<nameData>? data,}){
    _error = error;
    _message = message;
    _data = data;
}

  BankNameM.fromJson(dynamic json) {
    _error = json['error'];
    _message = json['message'];
    if (json['data'] != null) {
      _data = [];
      json['data'].forEach((v) {
        _data?.add(nameData.fromJson(v));
      });
    }
  }
  bool? _error;
  String? _message;
  List<nameData>? _data;
BankNameM copyWith({  bool? error,
  String? message,
  List<nameData>? data,
}) => BankNameM(  error: error ?? _error,
  message: message ?? _message,
  data: data ?? _data,
);
  bool? get error => _error;
  String? get message => _message;
  List<nameData>? get data => _data;

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    map['error'] = _error;
    map['message'] = _message;
    if (_data != null) {
      map['data'] = _data?.map((v) => v.toJson()).toList();
    }
    return map;
  }

}

/// BANK : "ABHYUDAYA COOPERATIVE BANK LIMITED"

class nameData {
  nameData({
      String? bank,}){
    _bank = bank;
}

  nameData.fromJson(dynamic json) {
    _bank = json['BANK'];
  }
  String? _bank;
  nameData copyWith({  String? bank,
}) => nameData(  bank: bank ?? _bank,
);
  String? get bank => _bank;

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    map['BANK'] = _bank;
    return map;
  }

}